"""
报告构建器 - 合并所有 HTML 片段生成最终报告

职责：
1. 收集所有 HTML 片段
2. 按顺序合并
3. 注入样式和脚本
4. 生成最终 HTML 文件
"""

from pathlib import Path
from datetime import datetime
from typing import Optional


class ReportBuilder:
    """
    报告构建器
    
    使用方式：
        builder = ReportBuilder("场景分析报告")
        builder.add_fragment(header_html)
        builder.add_fragment(stats_html)
        builder.add_fragments_from_dir("logs/workflows/xxx/fragments")
        output_path = builder.build("logs/report.html")
    """
    
    def __init__(self, title: str = "分析报告"):
        self.title = title
        self.fragments: list[str] = []
        self.custom_styles: list[str] = []
        self.custom_scripts: list[str] = []
    
    def add_fragment(self, fragment: str):
        """添加 HTML 片段"""
        self.fragments.append(fragment)
    
    def add_fragment_from_file(self, file_path: str):
        """从文件加载 HTML 片段"""
        path = Path(file_path)
        if path.exists():
            self.fragments.append(path.read_text(encoding="utf-8"))
    
    def add_fragments_from_dir(
        self,
        dir_path: str,
        order: list[str] = None
    ):
        """
        从目录按顺序加载所有片段
        
        Args:
            dir_path: 片段目录路径
            order: 文件名顺序列表（不含扩展名），如 ["01_header", "02_stats"]
        """
        dir_obj = Path(dir_path)
        if not dir_obj.exists():
            return
        
        if order:
            for name in order:
                fragment_file = dir_obj / f"{name}.html"
                if fragment_file.exists():
                    self.fragments.append(fragment_file.read_text(encoding="utf-8"))
        else:
            # 按文件名排序
            for f in sorted(dir_obj.glob("*.html")):
                self.fragments.append(f.read_text(encoding="utf-8"))
    
    def add_style(self, css: str):
        """添加自定义样式"""
        self.custom_styles.append(css)
    
    def add_script(self, js: str):
        """添加自定义脚本"""
        self.custom_scripts.append(js)
    
    def build(self, output_path: str) -> str:
        """
        生成最终报告
        
        Args:
            output_path: 输出文件路径
            
        Returns:
            输出文件的绝对路径
        """
        content = "\n".join(self.fragments)
        custom_styles = "\n".join(self.custom_styles)
        custom_scripts = "\n".join(self.custom_scripts)
        
        html = self._get_template().format(
            title=self.title,
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            base_styles=self._get_base_styles(),
            custom_styles=custom_styles,
            content=content,
            base_scripts=self._get_base_scripts(),
            custom_scripts=custom_scripts
        )
        
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(html, encoding="utf-8")
        
        return str(output.absolute())
    
    def _get_template(self) -> str:
        """获取 HTML 模板"""
        return """<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="generator" content="hana-perf workflow">
    <meta name="generated-at" content="{generated_at}">
    <style>
{base_styles}

{custom_styles}
    </style>
</head>
<body>
    <div class="report-container">
{content}
    </div>
    
    <footer class="report-footer">
        <p>Generated by hana-perf at {generated_at}</p>
    </footer>
    
    <script>
{base_scripts}

{custom_scripts}
    </script>
</body>
</html>
"""
    
    def _get_base_styles(self) -> str:
        """获取基础样式"""
        return """
/* ==================== 设计系统 ==================== */
:root {
    /* 主题色 - Cyberpunk 风格 */
    --color-bg: #0a0e17;
    --color-surface: #131a2b;
    --color-surface-alt: #1a2438;
    --color-border: #2a3a5a;
    
    --color-primary: #00d4ff;
    --color-primary-dim: #0099cc;
    --color-secondary: #ff6b9d;
    --color-accent: #7c3aed;
    
    --color-text: #e4e8f1;
    --color-text-dim: #8b95a8;
    --color-text-bright: #ffffff;
    
    --color-success: #10b981;
    --color-warning: #f59e0b;
    --color-error: #ef4444;
    --color-info: #3b82f6;
    
    /* 字体 */
    --font-sans: 'SF Pro Display', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    --font-mono: 'JetBrains Mono', 'SF Mono', 'Fira Code', monospace;
    
    /* 间距 */
    --spacing-xs: 4px;
    --spacing-sm: 8px;
    --spacing-md: 16px;
    --spacing-lg: 24px;
    --spacing-xl: 32px;
    --spacing-2xl: 48px;
    
    /* 圆角 */
    --radius-sm: 4px;
    --radius-md: 8px;
    --radius-lg: 12px;
    --radius-xl: 16px;
    
    /* 阴影 */
    --shadow-sm: 0 1px 2px rgba(0, 0, 0, 0.3);
    --shadow-md: 0 4px 12px rgba(0, 0, 0, 0.4);
    --shadow-lg: 0 8px 24px rgba(0, 0, 0, 0.5);
    --shadow-glow: 0 0 20px rgba(0, 212, 255, 0.3);
}

/* ==================== 基础样式 ==================== */
* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: var(--font-sans);
    background: var(--color-bg);
    color: var(--color-text);
    line-height: 1.6;
    min-height: 100vh;
}

.report-container {
    max-width: 1400px;
    margin: 0 auto;
    padding: var(--spacing-xl);
}

/* ==================== 报告头部 ==================== */
.report-header {
    background: linear-gradient(135deg, var(--color-surface) 0%, var(--color-surface-alt) 100%);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-xl);
    padding: var(--spacing-2xl);
    margin-bottom: var(--spacing-xl);
    position: relative;
    overflow: hidden;
}

.report-header::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 3px;
    background: linear-gradient(90deg, var(--color-primary), var(--color-secondary), var(--color-accent));
}

.header-title {
    font-size: 2.5rem;
    font-weight: 700;
    color: var(--color-text-bright);
    margin-bottom: var(--spacing-sm);
    text-shadow: 0 0 30px rgba(0, 212, 255, 0.3);
}

.header-subtitle {
    font-size: 1.1rem;
    color: var(--color-text-dim);
    margin-bottom: var(--spacing-md);
}

.header-meta {
    display: flex;
    flex-wrap: wrap;
    gap: var(--spacing-md);
    font-size: 0.9rem;
    color: var(--color-text-dim);
}

.meta-item {
    background: var(--color-bg);
    padding: var(--spacing-xs) var(--spacing-md);
    border-radius: var(--radius-md);
    border: 1px solid var(--color-border);
}

/* ==================== 区块样式 ==================== */
.section {
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-lg);
    padding: var(--spacing-lg);
    margin-bottom: var(--spacing-lg);
}

.section-title {
    font-size: 1.4rem;
    font-weight: 600;
    color: var(--color-text-bright);
    margin-bottom: var(--spacing-lg);
    padding-bottom: var(--spacing-md);
    border-bottom: 1px solid var(--color-border);
}

/* ==================== 统计卡片 ==================== */
.stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: var(--spacing-lg);
}

.stat-card {
    background: linear-gradient(145deg, var(--color-surface-alt), var(--color-surface));
    border: 1px solid var(--color-border);
    border-radius: var(--radius-lg);
    padding: var(--spacing-lg);
    text-align: center;
    transition: transform 0.2s, box-shadow 0.2s;
}

.stat-card:hover {
    transform: translateY(-2px);
    box-shadow: var(--shadow-glow);
    border-color: var(--color-primary);
}

.stat-icon {
    font-size: 1.5rem;
    margin-bottom: var(--spacing-sm);
}

.stat-value {
    font-size: 2.5rem;
    font-weight: 700;
    color: var(--color-primary);
    font-family: var(--font-mono);
    text-shadow: 0 0 20px rgba(0, 212, 255, 0.5);
}

.stat-label {
    font-size: 0.9rem;
    color: var(--color-text-dim);
    margin-top: var(--spacing-xs);
}

/* ==================== 垂直时间线 ==================== */
.timeline-vertical {
    padding: var(--spacing-md) 0;
}

.timeline-title {
    font-size: 1.2rem;
    color: var(--color-text-bright);
    margin-bottom: var(--spacing-lg);
}

.timeline-items {
    position: relative;
    padding-left: var(--spacing-2xl);
}

.timeline-items::before {
    content: '';
    position: absolute;
    left: 8px;
    top: 0;
    bottom: 0;
    width: 2px;
    background: linear-gradient(180deg, var(--color-primary), var(--color-secondary));
}

.timeline-item {
    position: relative;
    padding-bottom: var(--spacing-lg);
    display: grid;
    grid-template-columns: 100px 1fr;
    gap: var(--spacing-md);
}

.timeline-marker {
    position: absolute;
    left: -40px;
    top: 0;
    width: 18px;
    height: 18px;
    background: var(--color-surface);
    border: 2px solid var(--color-primary);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 10px;
    color: var(--color-primary);
}

.timeline-item--highlight .timeline-marker {
    background: var(--color-primary);
    box-shadow: 0 0 10px var(--color-primary);
}

.timeline-time {
    font-family: var(--font-mono);
    font-size: 0.85rem;
    color: var(--color-primary);
    white-space: nowrap;
}

.timeline-content {
    background: var(--color-surface-alt);
    border-radius: var(--radius-md);
    padding: var(--spacing-md);
    border: 1px solid var(--color-border);
}

.timeline-event-title {
    font-size: 1rem;
    font-weight: 500;
    color: var(--color-text-bright);
    margin-bottom: var(--spacing-xs);
}

.timeline-desc {
    font-size: 0.9rem;
    color: var(--color-text-dim);
}

/* ==================== 横向时间线 ==================== */
.timeline-horizontal {
    padding: var(--spacing-md) 0;
}

.progress-track {
    position: relative;
    height: 40px;
    background: var(--color-bg);
    border-radius: var(--radius-md);
    overflow: hidden;
    border: 1px solid var(--color-border);
}

.timeline-segment {
    position: absolute;
    top: 0;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: opacity 0.2s;
    overflow: hidden;
}

.timeline-segment:hover {
    opacity: 0.8;
}

.segment-label {
    font-size: 0.75rem;
    color: white;
    font-weight: 500;
    text-shadow: 0 1px 2px rgba(0,0,0,0.5);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    padding: 0 var(--spacing-xs);
}

.segment-tooltip {
    display: none;
    position: absolute;
    bottom: 100%;
    left: 50%;
    transform: translateX(-50%);
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    padding: var(--spacing-sm);
    border-radius: var(--radius-sm);
    font-size: 0.8rem;
    white-space: nowrap;
    z-index: 100;
    box-shadow: var(--shadow-md);
}

.timeline-segment:hover .segment-tooltip {
    display: block;
}

.time-axis {
    display: flex;
    justify-content: space-between;
    margin-top: var(--spacing-xs);
    font-size: 0.8rem;
    color: var(--color-text-dim);
    font-family: var(--font-mono);
}

/* ==================== 数据表格 ==================== */
.data-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.9rem;
}

.data-table th,
.data-table td {
    padding: var(--spacing-md);
    text-align: left;
    border-bottom: 1px solid var(--color-border);
}

.data-table th {
    background: var(--color-surface-alt);
    color: var(--color-text-bright);
    font-weight: 600;
    white-space: nowrap;
}

.data-table tr:hover {
    background: var(--color-surface-alt);
}

.data-table tr.highlight {
    background: rgba(0, 212, 255, 0.1);
}

/* ==================== 结论框 ==================== */
.conclusion-box {
    border-radius: var(--radius-lg);
    padding: var(--spacing-lg);
    margin: var(--spacing-md) 0;
    border: 1px solid;
}

.conclusion-box--info {
    background: rgba(59, 130, 246, 0.1);
    border-color: var(--color-info);
}

.conclusion-box--success {
    background: rgba(16, 185, 129, 0.1);
    border-color: var(--color-success);
}

.conclusion-box--warning {
    background: rgba(245, 158, 11, 0.1);
    border-color: var(--color-warning);
}

.conclusion-box--error {
    background: rgba(239, 68, 68, 0.1);
    border-color: var(--color-error);
}

.conclusion-title {
    font-size: 1.1rem;
    font-weight: 600;
    margin-bottom: var(--spacing-md);
    color: var(--color-text-bright);
}

/* ==================== 日志块 ==================== */
.log-block {
    background: var(--color-surface-alt);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    margin: var(--spacing-md) 0;
    overflow: hidden;
}

.log-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: var(--spacing-md);
    background: var(--color-surface);
    cursor: pointer;
    user-select: none;
}

.log-header:hover {
    background: var(--color-border);
}

.log-filename {
    font-weight: 500;
    color: var(--color-text-bright);
}

.log-meta {
    font-size: 0.85rem;
    color: var(--color-text-dim);
}

.log-content {
    max-height: 500px;
    overflow: auto;
}

.log-content pre {
    margin: 0;
    padding: var(--spacing-md);
    background: var(--color-bg);
    font-family: var(--font-mono);
    font-size: 0.8rem;
    line-height: 1.5;
    overflow-x: auto;
}

.log-truncated {
    padding: var(--spacing-sm) var(--spacing-md);
    background: var(--color-warning);
    color: var(--color-bg);
    font-size: 0.85rem;
    text-align: center;
}

/* ==================== 键值对列表 ==================== */
.kv-list {
    padding: var(--spacing-md) 0;
}

.kv-title {
    font-size: 1rem;
    color: var(--color-text-bright);
    margin-bottom: var(--spacing-md);
}

.kv-item {
    display: flex;
    justify-content: space-between;
    padding: var(--spacing-sm) 0;
    border-bottom: 1px dashed var(--color-border);
}

.kv-key {
    color: var(--color-text-dim);
}

.kv-value {
    color: var(--color-text-bright);
    font-family: var(--font-mono);
}

/* ==================== 标签列表 ==================== */
.tags {
    display: flex;
    flex-wrap: wrap;
    gap: var(--spacing-sm);
}

.tag {
    background: var(--color-surface-alt);
    border: 1px solid var(--color-border);
    padding: var(--spacing-xs) var(--spacing-md);
    border-radius: var(--radius-xl);
    font-size: 0.85rem;
    color: var(--color-text);
}

/* ==================== Activity 流程图 ==================== */
.activity-flow {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: var(--spacing-md);
    padding: var(--spacing-md) 0;
    overflow-x: auto;
}

.flow-item {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.flow-time {
    font-family: var(--font-mono);
    font-size: 0.75rem;
    color: var(--color-primary);
    margin-bottom: var(--spacing-xs);
}

.flow-box {
    background: var(--color-surface-alt);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    padding: var(--spacing-md);
    text-align: center;
    min-width: 150px;
}

.flow-package {
    font-size: 0.75rem;
    color: var(--color-text-dim);
    word-break: break-all;
}

.flow-activity {
    font-size: 0.9rem;
    color: var(--color-text-bright);
    font-weight: 500;
    margin-top: var(--spacing-xs);
}

.flow-arrow {
    font-size: 1.5rem;
    color: var(--color-primary);
}

/* ==================== 分隔线 ==================== */
.divider {
    border: none;
    height: 1px;
    background: linear-gradient(90deg, transparent, var(--color-border), transparent);
    margin: var(--spacing-xl) 0;
    display: flex;
    align-items: center;
    justify-content: center;
}

.divider span {
    background: var(--color-surface);
    padding: 0 var(--spacing-md);
    color: var(--color-text-dim);
    font-size: 0.9rem;
}

/* ==================== 页脚 ==================== */
.report-footer {
    text-align: center;
    padding: var(--spacing-xl);
    color: var(--color-text-dim);
    font-size: 0.85rem;
    border-top: 1px solid var(--color-border);
    margin-top: var(--spacing-2xl);
}

/* ==================== 响应式 ==================== */
@media (max-width: 768px) {
    .report-container {
        padding: var(--spacing-md);
    }
    
    .header-title {
        font-size: 1.8rem;
    }
    
    .stats-grid {
        grid-template-columns: repeat(2, 1fr);
    }
    
    .timeline-item {
        grid-template-columns: 1fr;
    }
    
    .timeline-time {
        margin-bottom: var(--spacing-xs);
    }
    
    .activity-flow {
        flex-direction: column;
    }
    
    .flow-arrow {
        transform: rotate(90deg);
    }
}
"""
    
    def _get_base_scripts(self) -> str:
        """获取基础脚本"""
        return """
// 日志块折叠切换
document.querySelectorAll('.log-block summary').forEach(summary => {
    summary.addEventListener('click', (e) => {
        // 默认行为已由 <details> 处理
    });
});

// 时间线段点击高亮
document.querySelectorAll('.timeline-segment').forEach(segment => {
    segment.addEventListener('click', () => {
        document.querySelectorAll('.timeline-segment').forEach(s => {
            s.style.opacity = '0.5';
        });
        segment.style.opacity = '1';
    });
});

// 表格排序（可选）
document.querySelectorAll('.data-table.sortable th').forEach(th => {
    th.style.cursor = 'pointer';
    th.addEventListener('click', () => {
        const table = th.closest('table');
        const tbody = table.querySelector('tbody');
        const rows = Array.from(tbody.querySelectorAll('tr'));
        const index = Array.from(th.parentElement.children).indexOf(th);
        
        const sorted = rows.sort((a, b) => {
            const aText = a.children[index].textContent;
            const bText = b.children[index].textContent;
            return aText.localeCompare(bText);
        });
        
        sorted.forEach(row => tbody.appendChild(row));
    });
});

console.log('Report loaded successfully');
"""

